eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  cloud:
    config:
      override-system-properties: false

DB_URL: ${PROD_DB_URL}
ADDITIONAL_PROP: ${PROD_ADDITIONAL_PROP}
DB_USERNAME: ${PROD_DB_USERNAME}
DB_PASSWORD: ${PROD_DB_PASSWORD}