springdoc:
  swagger-ui:
    path: /api/v1/auth/anonymous/swagger-ui.html
  api-docs:
    path: /api/v1/auth/anonymous/v3/api-docs
openapi:
  title: Authentication API Document
  version: 1.0
  description: Authentication API Service
  serverURL:
  serverName: serverTest

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}/authentication${ADDITIONAL_PROP}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform:  org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "https://95d2-113-22-113-75.ngrok-free.app/oauth2/callback"
            scope:
              - email
              - profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo

  flyway:
    repair: true
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  redis:
    host: localhost
    port: 6379
    timeout: 2000
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: -1
      retries: 1
      properties:
        enable:
          idempotence: true
        max:
          in:
            flight:
              request:
                per:
                  connection: 5
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      auto-offset-reset: earliest
server:
  port: 5554
  forward-headers-strategy: framework

JWT_SECRET_KEY: ${JWT_SECRET_KEY}