springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enable: true
    path: /swagger-ui.html
    urls:
      - url: /v3/api-docs/customer-service
        name: Customer Service
      - url: /v3/api-docs/order-service
        name: Order Service
      - url: /v3/api-docs/railcar-service
        name: Railcar Service
      - url: /v3/api-docs/train-service
        name: Train Service
      - url: /v3/api-docs/ticket-service
        name: Ticket Service
      - url: /v3/api-docs/route-service
        name: Route Service
      - url: /v3/api-docs/schedule-service
        name: Schedule Service
      - url: /v3/api-docs/station-service
        name: Station Service
      - url: /v3/api-docs/authentication-service
        name: Authentication Service
      - url: /v3/api-docs/role-service
        name: Role Service

spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: -1
      retries: 1
      properties:
        enable:
          idempotence: true
        max:
          in:
            flight:
              request:
                per:
                  connection: 5
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
  redis:
    host: localhost
    port: 6379
    timeout: 2000
  cloud:
    loadbalancer:
      sticky-session:
        enabled: true
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "Content-Type"
              - "X-Auth-Token"
              - "Origin"
              - "Authorization"
            allowCredentials: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: authentication-websocket-route
          uri: lb:ws://AUTHENTICATION-SERVICE  # URL của dịch vụ Authentication chạy WebSocket
          predicates:
            - Path=/websocket/auth  # Đường dẫn WebSocket
          filters:
            - PreserveHostHeader
            - RewriteResponseHeader=Upgrade,websocket
            - RewriteResponseHeader=Connection,upgrade
            - AddRequestHeader=Sec-WebSocket-Version,13
            - AddRequestHeader=Sec-WebSocket-Key,vO/qpi5TM/g4ypQsIuH/xQ==
            - AddRequestHeader=Sec-WebSocket-Extensions,permessage-deflate; client_max_window_bits
        - id: oauth2-auth-service
          uri: lb://AUTHENTICATION-SERVICE # Tên của Auth-Service
          predicates:
            - Path=/login/**, /oauth2/**, /callback/**
          filters:
            - PreserveHostHeader
        - id: customer-service
          uri: lb:http://CUSTOMER-SERVICE
          predicates:
            - Path=/api/v1/customer/**
          filters:
            - AuthenticationFilter
        - id: order-service
          uri: lb:http://ORDER-SERVICE
          predicates:
            - Path=/api/v1/order/**
          filters:
            - AuthenticationFilter
        - id: statistic-service
          uri: lb:http://STORE-SERVICE
          predicates:
            - Path=/api/v1/statistic/**
          filters:
            - AuthenticationFilter
        - id: store-service
          uri: lb:http://STORE-SERVICE
          predicates:
            - Path=/api/v1/store/**
          filters:
            - AuthenticationFilter
        - id: railcar-service
          uri: lb:http://STORE-SERVICE
          predicates:
            - Path=/api/v1/railcar/**
          filters:
            - AuthenticationFilter
        - id: payment-service
          uri: lb:http://PAYMENT-SERVICE
          predicates:
            - Path=/api/v1/payment/**
          filters:
            - AuthenticationFilter
        - id: train-service
          uri: lb:http://STORE-SERVICE
          predicates:
            - Path=/api/v1/train/**
          filters:
            - AuthenticationFilter
        - id: ticket-service
          uri: lb:http://STORE-SERVICE
          predicates:
            - Path=/api/v1/ticket/**
          filters:
            - AuthenticationFilter
        - id: route-service
          uri: lb:http://STORE-SERVICE
          predicates:
            - Path=/api/v1/route/**
          filters:
            - AuthenticationFilter
        - id: schedule-service
          uri: lb:http://STORE-SERVICE
          predicates:
            - Path=/api/v1/schedule/**
          filters:
            - AuthenticationFilter
        - id: station-service
          uri: lb:http://STORE-SERVICE
          predicates:
            - Path=/api/v1/station/**
          filters:
            - AuthenticationFilter
        - id: station-service
          uri: lb:http://STORE-SERVICE
          predicates:
            - Path=/api/v1/monitoring/**
          filters:
            - AuthenticationFilter
        - id: marketing-service
          uri: lb:http://MARKETING-SERVICE
          predicates:
            - Path=/api/v1/marketing/**
          filters:
            - AuthenticationFilter
        - id: shipment-service
          uri: lb:http://SHIPMENT-SERVICE
          predicates:
            - Path=/api/v1/shipment/**
          filters:
            - AuthenticationFilter
        - id: category-service
          uri: lb:http://STORE-SERVICE
          predicates:
             - Path=/api/v1/category/**
          filters:
              - AuthenticationFilter
        - id: authentication-service
          uri: lb:http://AUTHENTICATION-SERVICE
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - AuthenticationFilter
            - PreserveHostHeader
        - id: role-service
          uri: lb:http://AUTHENTICATION-SERVICE
          predicates:
            - Path=/api/v1/role/**
          filters:
            - AuthenticationFilter
  main:
    allow-circular-references: true
server:
  port: 8031


JWT_SECRET_KEY: ${JWT_SECRET_KEY}
