springdoc:
  swagger-ui:
    path: /api/v1/order/anonymous/swagger-ui.html
  api-docs:
    path: /api/v1/order/anonymous/v3/api-docs
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}/order${ADDITIONAL_PROP}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform:  org.hibernate.dialect.PostgreSQLDialect
  flyway:
    repair: true
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  redis:
    host: localhost
    port: 6379
    timeout: 2000
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: -1
      retries: 1
      properties:
        enable:
          idempotence: true
        max:
          in:
            flight:
              request:
                per:
                  connection: 5
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      auto-offset-reset: earliest
server:
  port: 5557