INSERT INTO address (street, city, state, postal_code, created_date, last_modified_date) VALUES
                                                                                             ('120 Lê Duẩn', 'Hà Nội', 'Hà Nội', '100000', NOW(), NOW()),
                                                                                             ('1 Nguyễn Huệ', 'Hải Phòng', 'Hải Phòng', '200000', NOW(), NOW()),
                                                                                             ('10 Trần Phú', 'Thanh Hóa', 'Thanh Hóa', '440000', NOW(), NOW()),
                                                                                             ('27 Lê Duẩn', 'Vinh', 'Nghệ An', '460000', NOW(), NOW()),
                                                                                             ('31 Lê Lợi', 'Huế', 'Thừa Thiên Huế', '530000', NOW(), NOW()),
                                                                                             ('40 Trần Hưng Đạo', 'Đà Nẵng', 'Đà Nẵng', '550000', NOW(), NOW()),
                                                                                             ('55 Nguyễn Thái Học', 'Quảng Nam', 'Quảng Nam', '560000', NOW(), NOW()),
                                                                                             ('66 Nguyễn Huệ', 'Quảng Ngãi', 'Quảng Ngãi', '570000', NOW(), NOW()),
                                                                                             ('75 Trần Phú', 'Bình Định', 'Bình Định', '580000', NOW(), NOW()),
                                                                                             ('85 Nguyễn Huệ', 'Phú Yên', 'Phú Yên', '590000', NOW(), NOW()),
                                                                                             ('95 Trần Hưng Đạo', 'Khánh Hòa', 'Khánh Hòa', '650000', NOW(), NOW()),
                                                                                             ('105 Nguyễn Thái Học', 'Ninh Thuận', 'Ninh Thuận', '670000', NOW(), NOW()),
                                                                                             ('115 Trần Hưng Đạo', 'Bình Thuận', 'Bình Thuận', '670000', NOW(), NOW()),
                                                                                             ('125 Nguyễn Huệ', 'Bà Rịa - Vũng Tàu', 'Bà Rịa - Vũng Tàu', '790000', NOW(), NOW()),
                                                                                             ('135 Lê Lợi', 'Hồ Chí Minh', 'TP.HCM', '700000', NOW(), NOW()),
                                                                                             ('145 Nguyễn Văn Cừ', 'Tiền Giang', 'Tiền Giang', '800000', NOW(), NOW()),
                                                                                             ('155 Trần Phú', 'Long An', 'Long An', '850000', NOW(), NOW()),
                                                                                             ('165 Nguyễn Thái Học', 'Tây Ninh', 'Tây Ninh', '840000', NOW(), NOW()),
                                                                                             ('175 Lê Duẩn', 'Bình Dương', 'Bình Dương', '750000', NOW(), NOW()),
                                                                                             ('185 Nguyễn Văn Cừ', 'Bình Phước', 'Bình Phước', '670000', NOW(), NOW()),
                                                                                             ('195 Trần Hưng Đạo', 'Cần Thơ', 'Cần Thơ', '900000', NOW(), NOW()),
                                                                                             ('205 Lê Lợi', 'Hậu Giang', 'Hậu Giang', '930000', NOW(), NOW()),
                                                                                             ('215 Nguyễn Huệ', 'Sóc Trăng', 'Sóc Trăng', '930000', NOW(), NOW()),
                                                                                             ('225 Trần Phú', 'Bạc Liêu', 'Bạc Liêu', '980000', NOW(), NOW()),
                                                                                             ('235 Nguyễn Văn Cừ', 'Cà Mau', 'Cà Mau', '990000', NOW(), NOW());

-- Các ga thuộc khu vực phía Bắc
INSERT INTO station (address_id, name, created_date, last_modified_date) VALUES
                                                                             (1, 'Ga Hà Nội', NOW(), NOW()),
                                                                             (2, 'Ga Hải Phòng', NOW(), NOW()),
                                                                             (3, 'Ga Thanh Hóa', NOW(), NOW()),
                                                                             (4, 'Ga Vinh', NOW(), NOW()),
                                                                             (5, 'Ga Huế', NOW(), NOW()),
                                                                             (6, 'Ga Đà Nẵng', NOW(), NOW()),
                                                                             (7, 'Ga Quảng Nam', NOW(), NOW()),
                                                                             (8, 'Ga Quảng Ngãi', NOW(), NOW()),
                                                                             (9, 'Ga Bình Định', NOW(), NOW()),
                                                                             (10, 'Ga Phú Yên', NOW(), NOW()),
                                                                             (11, 'Ga Khánh Hòa', NOW(), NOW()),
                                                                             (12, 'Ga Ninh Thuận', NOW(), NOW()),
                                                                             (13, 'Ga Bình Thuận', NOW(), NOW()),

-- Các ga thuộc khu vực miền Nam
                                                                             (14, 'Ga Hồ Chí Minh', NOW(), NOW()),
                                                                             (15, 'Ga Tiền Giang', NOW(), NOW()),
                                                                             (16, 'Ga Long An', NOW(), NOW()),
                                                                             (17, 'Ga Tây Ninh', NOW(), NOW()),
                                                                             (18, 'Ga Bình Dương', NOW(), NOW()),
                                                                             (19, 'Ga Bình Phước', NOW(), NOW()),
                                                                             (20, 'Ga Cần Thơ', NOW(), NOW()),
                                                                             (21, 'Ga Hậu Giang', NOW(), NOW()),
                                                                             (22, 'Ga Sóc Trăng', NOW(), NOW()),
                                                                             (23, 'Ga Bạc Liêu', NOW(), NOW()),
                                                                             (24, 'Ga Cà Mau', NOW(), NOW());